swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport:        "%mailer_transport%"
    username:         "%mailer_user%"
    password:         "%mailer_password%"
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
