#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# DefaultController Routes
signup:
  path: /signup/{invite}
  controller: App\Controller\DefaultController::signup

login:
  path: /login
  controller: App\Controller\DefaultController::login


homepage:
  path:     /
  controller: App\Controller\DefaultController::homepage

# QuestionController Routes


# Profile Routes

account_settings:
  path: /profile/settings
  controller: App\Controller\AccountController::editAccount

passwordChange:
  path: /profile/settings/password
  controller: App\Controller\AccountController::changePassword
 

# AdminController Routes
admin:
  path: /admin
  controller: App\Controller\AdminController::admin

invite:
  path: /admin/invite
  controller: App\Controller\AdminController::userInvite

deleteInvite:
  path: /admin/invite/delete{invite}
  controller: App\Controller\AdminController::deleteInvite  

inviteList:
  path: /admin/inviteList
  controller: App\Controller\AdminController::listInvites  

userList:
  path: /admin/userList
  controller: App\Controller\AdminController::userList

departmentList:
  path: /admin/department
  controller: App\Controller\AdminController::departmentList

makeAdmin:
  path: /admin/userList/makeAdmin{user}
  controller: App\Controller\AdminController::makeAdmin
     
makeUser:
  path: /admin/userList/makeUser/{user}
  controller: App\Controller\AdminController::makeUser 

makeInactive:
  path: /admin/userList/deactivate/{user}
  controller: App\Controller\AdminController::makeInactive  

