#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# DefaultController Routes
signup:
  path: /signup/{invite}
  controller: App\Controller\DefaultController::signup

login:
  path: /login
  controller: App\Controller\DefaultController::login


homepage:
  path:     /
  controller: App\Controller\DefaultController::homepage

# QuestionController Routes
 

# AdminController Routes

admin_default:
  path:     /admin
  controller: App\Controller\AdminController::default

invite:
  path: /admin/invite
  controller: App\Controller\AdminController::userInvite

inviteList:
  path: /admin/inviteList
  controller: App\Controller\AdminController::listInvites  

userList:
  path: /admin/departmentDetail
  controller: App\Controller\AdminController::departmentDetail

userList:
  path: /admin/userList
  controller: App\Controller\AdminController::userList

userDetail:
  path: /admin/userDetail/{user}
  controller: App\Controller\AdminController::userDetail

makeAdmin:
  path: /admin/userList/{user}
  controller: App\Controller\AdminController::makeAdmin
     
removeAdmin:
  path: /admin/userList/remove/{user}
  controller: App\Controller\AdminController::removeAdmin 

deactivateUser:
  path: /admin/userList/deactivate/{user}
  controller: App\Controller\AdminController::deactivateUser   

