#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# DefaultController Routes
signup:
  path: /signup/{invite}
  controller: App\Controller\DefaultController::signup

login:
  path: /login
  controller: App\Controller\DefaultController::login

homepage:
  path:     /
  controller: App\Controller\DefaultController::homepage

question:
  path:     /questions
  controller: App\Controller\DefaultController::question

# QuestionController Routes
 
questionAnswer:
  path:     /question/{question}
  controller: App\Controller\QuestionController::questionAnswer

# AdminController Routes

invite:
  path: /admin/invite
  controller: App\Controller\AdminController::userInvite